  
    <div id="loginbox" style="margin-top:50px; margin-left: 15%" class="mainbox col-lg-15" >                    
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Login</div>
            </div>     

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <form id="loginform" action="/acesso/login" method="post" class="form-horizontal" role="form">

                    <div style="margin-bottom: 15px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="Usuário">                                        
                    </div>

                    <div style="margin-bottom: 5px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password" placeholder="Senha">
                    </div>



                    <div class="input-group">
                        <div class="checkbox">
                            <label>
                                <input id="login-remember" type="checkbox" name="remember" value="1"> Lembrar
                            </label>
                        </div>
                    </div>
                    
                    <div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Esqueceu a senha?</a></div>
                    </div>


                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->

                        <div class="col-sm-12 controls">
                            <button id="btn-login" href="#" class="btn btn-info">Login  </button>
                            <!--<a id="btn-fblogin" href="#" class="btn btn-primary">Login com Facebook</a>-->

                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-lg-36 control">
                            <div style="padding-top:15px; font-size:85%" >
                                Não tem uma conta! 
                                <a href="#">  Crie uma agora. </a>
                            </div>
                        </div>
                    </div>    
                </form>     



            </div>                     
        </div>  
    </div>
    